window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\laptop house\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\LOCAL\\crashpad_4044_ZGZMHHCXPFIIWLCD",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-311Q0EP",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\laptop house\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\laptop house",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\laptop house",
  "INIT_CWD": "C:\\Users\\laptop house\\Documents\\VS Code Projects\\React-Countdown",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\laptop house\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-311Q0EP",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\laptop house\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\laptop house\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\laptop house\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\laptop house\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\laptop house\\Documents\\VS Code Projects\\React-Countdown",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\laptop house\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\laptop house\\.npmrc",
  "npm_config_user_agent": "npm/8.19.2 node/v18.12.1 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\laptop house\\Documents\\VS Code Projects\\React-Countdown\\package.json",
  "npm_package_name": "countdown",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\laptop house\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "4",
  "OneDrive": "C:\\Users\\laptop house\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\laptop house\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\laptop house\\Documents\\VS Code Projects\\React-Countdown\\node_modules\\.bin;C:\\Users\\laptop house\\Documents\\VS Code Projects\\node_modules\\.bin;C:\\Users\\laptop house\\Documents\\node_modules\\.bin;C:\\Users\\laptop house\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\laptop house\\Documents\\VS Code Projects\\React-Countdown\\node_modules\\.bin;C:\\Users\\laptop house\\Documents\\VS Code Projects\\node_modules\\.bin;C:\\Users\\laptop house\\Documents\\node_modules\\.bin;C:\\Users\\laptop house\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;F:\\app\\laptophouse\\product\\11.2.0\\dbhome_1\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Users\\laptop house\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\laptop house\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\laptop house\\AppData\\Roaming\\npm;C:\\Users\\laptop house\\.dotnet\\tools",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 142 Stepping 9, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8e09",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\laptop house\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\PowerShell\\Modules\\",
  "PUBLIC": "C:\\Users\\Public",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\LAPTOP~1\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.74.3",
  "TMP": "C:\\Users\\LAPTOP~1\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-311Q0EP",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-311Q0EP",
  "USERNAME": "laptop house",
  "USERPROFILE": "C:\\Users\\laptop house",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\laptop house\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\laptop house\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-326af9c204-sock",
  "VSCODE_INJECTION": "1",
  "windir": "C:\\Windows"
};